- hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: host_vars

    - name: Create a virtual machine from a template
      local_action:
        module: vmware_guest
        hostname: "{{ vcenter_ip}}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        validate_certs: False
        folder: vm
        name: atomic000
        state: poweredoff
        guest_id: centos64Guest
        disk:
        - size_gb: 50
          type: thick
          datastore: datastore1
        hardware:
          memory_mb: 2048
          num_cpus: 8
          scsi: paravirtual
          memory_reservation: 512
          memory_reservation_lock: True
          mem_limit: 8096
          mem_reservation: 4096
          cpu_limit: 8096
          cpu_reservation: 4096
          max_connections: 5
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
          version: 10 # Hardware version of virtual machine
          boot_firmware: "efi"
        cdrom:
          type: iso
          iso_path: "[datastore1] ISO/CentOS-Atomic-Host-Installer.iso"
        networks:
        - name: VM Network
          mac: aa:bb:dd:aa:00:14
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy

    - name: Print the state of a virtual machine
      debug:
        msg: "{{ deploy }}"

    - name: Set the state of a virtual machine to poweron
      local_action:
        module: vmware_guest_powerstate
        hostname: "{{ vcenter_ip}}"
        username: "{{ vcenter_username}}"
        password: "{{ vcenter_password}}"
        validate_certs: False
        name: "{{ guest_name }}"
        state: powered-on
      delegate_to: localhost
      register: deploy

    - name: Print the state of a virtual machine
      debug:
        msg: "{{ deploy }}"

